###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

# Just an example use case
# enable_analytics: no
_site_root: /weisman/statamic/
_site_url: ~philippe/weisman/statamic/